#!/bin/bash
###########################################################
# Blockbridge volume driver entrypoint
###########################################################

# Validate environment parameters
: ${BLOCKBRIDGE_API_HOST:?"not set"}
: ${BLOCKBRIDGE_API_KEY:?"not set"}
: ${BLOCKBRIDGE_ROOT="/bb"}

export BLOCKBRIDGE_ROOT
export RUBYLIB="$RUBYLIB:app"

# run blockbridge volume driver
exec ruby -rbundler/setup app/volume.rb -S /run/docker/plugins/blockbridge/blockbridge.sock
