#!/bin/bash
###########################################################
# Blockbridge volume driver entrypoint
###########################################################

# Validate environment parameters
: ${BLOCKBRIDGE_API_HOST:?"not set"}
: ${BLOCKBRIDGE_API_KEY:?"not set"}
: ${BLOCKBRIDGE_ROOT:?"not set"}

export BLOCKBRIDGE_ROOT
export RUBYLIB="$RUBYLIB:app"

trap '' TERM

# run blockbridge volume driver
mkdir -p /run/docker/plugins/blockbridge
ruby -rbundler/setup app/driver.rb -e production -S /run/docker/plugins/blockbridge/blockbridge.sock
